// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProfitAndLossReport_BoldColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfitAndLossReport_BoldColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201602092211512_ProfitAndLossReport_BoldColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
